/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab4;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Bai1 extends javax.swing.JFrame {

    /**
     * Creates new form Bai1
     */
    public Bai1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnNewmenu = new javax.swing.JButton();
        btnAboutmenu = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtFpoly = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txpText = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuNewFile = new javax.swing.JMenuItem();
        menuFileOpen = new javax.swing.JMenuItem();
        menuFileSave = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuColorRed = new javax.swing.JRadioButtonMenuItem();
        menuColorGreen = new javax.swing.JRadioButtonMenuItem();
        menuColorBlue = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuTextColor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnNewmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-add-file-40.png"))); // NOI18N
        btnNewmenu.setFocusable(false);
        btnNewmenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewmenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewmenuActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNewmenu);

        btnAboutmenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-person-40.png"))); // NOI18N
        btnAboutmenu.setFocusable(false);
        btnAboutmenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAboutmenu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAboutmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutmenuActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAboutmenu);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-shutdown-40.png"))); // NOI18N
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);

        txtFpoly.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFpoly.setText("                                                         Fpoly - Java3");

        jScrollPane2.setViewportView(txpText);

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        menuNewFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuNewFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-add-file-40.png"))); // NOI18N
        menuNewFile.setText("New");
        menuNewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewFileActionPerformed(evt);
            }
        });
        jMenu1.add(menuNewFile);

        menuFileOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuFileOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-opened-folder-40.png"))); // NOI18N
        menuFileOpen.setText("Open");
        menuFileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileOpenActionPerformed(evt);
            }
        });
        jMenu1.add(menuFileOpen);

        menuFileSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menuFileSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-save-close-40.png"))); // NOI18N
        menuFileSave.setText("Save");
        menuFileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileSaveActionPerformed(evt);
            }
        });
        jMenu1.add(menuFileSave);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Color");

        menuColorRed.setText("Red");
        menuColorRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuColorRedActionPerformed(evt);
            }
        });
        jMenu2.add(menuColorRed);

        menuColorGreen.setText("Green");
        menuColorGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuColorGreenActionPerformed(evt);
            }
        });
        jMenu2.add(menuColorGreen);

        menuColorBlue.setText("Blue");
        menuColorBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuColorBlueActionPerformed(evt);
            }
        });
        jMenu2.add(menuColorBlue);
        jMenu2.add(jSeparator1);

        menuTextColor.setText("Text Color");
        menuTextColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTextColorActionPerformed(evt);
            }
        });
        jMenu2.add(menuTextColor);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("System");

        menuAbout.setText("About us");
        menuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAboutActionPerformed(evt);
            }
        });
        jMenu3.add(menuAbout);

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu3.add(menuExit);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtFpoly, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFpoly, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát?");
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnNewmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewmenuActionPerformed
        // TODO add your handling code here:
        txpText.setText("");
    }//GEN-LAST:event_btnNewmenuActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát?");
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuColorBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuColorBlueActionPerformed
        // TODO add your handling code here:
        txtFpoly.setBackground(Color.blue);
    }//GEN-LAST:event_menuColorBlueActionPerformed

    private void menuColorGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuColorGreenActionPerformed
        // TODO add your handling code here:
        txtFpoly.setBackground(Color.green);
    }//GEN-LAST:event_menuColorGreenActionPerformed

    private void menuColorRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuColorRedActionPerformed
        // TODO add your handling code here:
        txtFpoly.setBackground(Color.red);
    }//GEN-LAST:event_menuColorRedActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void menuFileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileSaveActionPerformed
        // TODO add your handling code here:
//        JFileChooser fChooser = new JFileChooser();
//        int result = fChooser.showSaveDialog(null);
//        if (result == JFileChooser.APPROVE_OPTION) {
//            File fname = fChooser.getSelectedFile();
//            try {
//                PrintWriter pw = new PrintWriter(fname);
//                pw.println(edPage.getText());
//                pw.close();
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//        }
        int tl = JOptionPane.showConfirmDialog(null, "Ban co muon luu file?", "Yes/No", JOptionPane.YES_NO_CANCEL_OPTION);
        switch (tl) {
            case 0:
                //kiểm tra sự chọn lựa của người dùng
                String s = txpText.getText(); //lấy đoạn văn bản đã soạn thảo
                //mở hộp thoại lưu File, và lấy đường dẫn người dùng đã chọn
                JFileChooser fileChooser = new JFileChooser("D:/");
                fileChooser.showSaveDialog(this);
                File file = fileChooser.getSelectedFile();
                //ghi dữ liệu vào file
                try {
                    try (FileOutputStream f = new FileOutputStream(file)) {
                        byte[] buff = new byte[1024];
                        buff = s.getBytes();
                        f.write(buff);
                    }
                    txpText.setText("");
                } catch (IOException e) {
                }
                break;
            case 1:
                txpText.setText("");
                break;
            default:
                ;
                break;
        }
    }//GEN-LAST:event_menuFileSaveActionPerformed

    private void menuFileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileOpenActionPerformed
        // TODO add your handling code here:
//        JFileChooser fchooser = new JFileChooser();
//        int result = fchooser.showOpenDialog(null);
//        if (result == JFileChooser.APPROVE_OPTION) {
//            try {
//                edPage.setPage("file:///" + fchooser.getSelectedFile().getPath());
//            } catch (Exception e) {
//                e.printStackTrace();
//            }
//        }
        JFileChooser dialogOpen = new JFileChooser();
        dialogOpen.showOpenDialog(this);
        File fileOpen = dialogOpen.getSelectedFile();
        try {  //đọc file ra vùng soạn thảo.
            FileInputStream file = new FileInputStream(fileOpen);
            byte[] buff = new byte[file.available()];
            file.read(buff);
            String s = new String(buff);
            txpText.enable(true);
            txpText.setText(s);
        } catch (IOException e) {
        }
    }//GEN-LAST:event_menuFileOpenActionPerformed

    private void menuNewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewFileActionPerformed
        // TODO add your handling code here:
        txpText.setText("");
    }//GEN-LAST:event_menuNewFileActionPerformed

    private void menuTextColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTextColorActionPerformed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(null, "Chọn màu", Color.white);
        txtFpoly.setForeground(c);
    }//GEN-LAST:event_menuTextColorActionPerformed

    private void menuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAboutActionPerformed
        // TODO add your handling code here:
        showAboutUs();
    }//GEN-LAST:event_menuAboutActionPerformed

    private void btnAboutmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutmenuActionPerformed
        // TODO add your handling code here:
        showAboutUs();
    }//GEN-LAST:event_btnAboutmenuActionPerformed
    private void showAboutUs() {
        String str = "Program Demo Menu";
        str += "\nAuthor: Đồng Đồng";
        str += "\nLast Update: 7-21-2020";
        str += "\nEducation: Fpoly";
        JOptionPane.showMessageDialog(null, str, "Giới thiệu", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Bai1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAboutmenu;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNewmenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JRadioButtonMenuItem menuColorBlue;
    private javax.swing.JRadioButtonMenuItem menuColorGreen;
    private javax.swing.JRadioButtonMenuItem menuColorRed;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuFileOpen;
    private javax.swing.JMenuItem menuFileSave;
    private javax.swing.JMenuItem menuNewFile;
    private javax.swing.JMenuItem menuTextColor;
    private javax.swing.JTextPane txpText;
    private javax.swing.JTextField txtFpoly;
    // End of variables declaration//GEN-END:variables
}
