/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab4;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class BaiThem extends javax.swing.JFrame {

    /**
     * Creates new form BaiThem
     */
    public BaiThem() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnNew = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpEdit = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnWindow = new javax.swing.JMenu();
        mnClose = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnNew.setText("New");
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNew);

        btnOpen.setText("Open");
        btnOpen.setFocusable(false);
        btnOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOpen);

        btnSave.setText("Save");
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSave);

        jScrollPane1.setViewportView(txpEdit);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        mnWindow.setText("Window");
        mnWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnWindowActionPerformed(evt);
            }
        });

        mnClose.setText("Close");
        mnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCloseActionPerformed(evt);
            }
        });
        mnWindow.add(mnClose);

        jMenuBar1.add(mnWindow);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        int tl = JOptionPane.showConfirmDialog(null, "Ban co muon luu file?", "Yes/No", JOptionPane.YES_NO_CANCEL_OPTION);
        if (tl == 0) { //kiểm tra sự chọn lựa của người dùng
            String s = txpEdit.getText(); //lấy đoạn văn bản đã soạn thảo
            //mở hộp thoại lưu File, và lấy đường dẫn người dùng đã chọn
            JFileChooser fileChooser = new JFileChooser("D:/");
            fileChooser.showSaveDialog(this);
            File file = fileChooser.getSelectedFile();
            //ghi dữ liệu vào file
            try {
                FileOutputStream f = new FileOutputStream(file);
                byte[] buff = new byte[1024];
                buff = s.getBytes();
                f.write(buff);
                f.close();
                txpEdit.setText("");
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (tl == 1) {
            txpEdit.setText("");
        } else
              ;

    }//GEN-LAST:event_btnNewActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        JFileChooser dialogOpen = new JFileChooser();
        dialogOpen.showOpenDialog(this);
        File fileOpen = dialogOpen.getSelectedFile();
        try {  //đọc file ra vùng soạn thảo.
            FileInputStream file = new FileInputStream(fileOpen);
            byte[] buff = new byte[file.available()];
            file.read(buff);
            String s = new String(buff);
            txpEdit.enable(true);
            txpEdit.setText(s);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int tl = JOptionPane.showConfirmDialog(null, "Ban co muon luu file?", "Yes/No", JOptionPane.YES_NO_CANCEL_OPTION);
        if (tl == 0) { //kiểm tra sự chọn lựa của người dùng
            String s = txpEdit.getText(); //lấy đoạn văn bản đã soạn thảo
            //mở hộp thoại lưu File, và lấy đường dẫn người dùng đã chọn
            JFileChooser fileChooser = new JFileChooser("D:/");
            fileChooser.showSaveDialog(this);
            File file = fileChooser.getSelectedFile();
            //ghi dữ liệu vào file
            try {
                FileOutputStream f = new FileOutputStream(file);
                byte[] buff = new byte[1024];
                buff = s.getBytes();
                f.write(buff);
                f.close();
                txpEdit.setText("");
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else if (tl == 1) {
            txpEdit.setText("");
        } else
              ;


    }//GEN-LAST:event_btnSaveActionPerformed

    private void mnWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnWindowActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mnWindowActionPerformed

    private void mnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCloseActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát?");
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_mnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaiThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaiThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaiThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaiThem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaiThem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnClose;
    private javax.swing.JMenu mnWindow;
    private javax.swing.JTextPane txpEdit;
    // End of variables declaration//GEN-END:variables
}
